### ISSUE TITLE
Problem running mity - undefined symbol  __intel_sse2_strcpy

### ISSUE THREAD

**Issue by rkabiljo** [KCCG/mity#32]
Hello,

I have  installed mitt with pip3, python 3.7.4. The installation went fine, but it does not run:

$ mity --h
Traceback (most recent call last):
  File "/home/skgtrk2/miniconda3/envs/py374/bin/mity", line 12, in <module>
    from mitylib import commands
  File "/home/skgtrk2/miniconda3/envs/py374/lib/python3.7/site-packages/mitylib/__init__.py", line 2, in <module>
    from .commands import *
  File "/home/skgtrk2/miniconda3/envs/py374/lib/python3.7/site-packages/mitylib/commands.py", line 13, in <module>
    from . import (call, normalise, report, merge)
  File "/home/skgtrk2/miniconda3/envs/py374/lib/python3.7/site-packages/mitylib/call.py", line 6, in <module>
    from .util import tabix, check_missing_file, create_prefix, bam_get_mt_contig, bam_has_RG
  File "/home/skgtrk2/miniconda3/envs/py374/lib/python3.7/site-packages/mitylib/util.py", line 8, in <module>
    import pysam
  File "/home/skgtrk2/miniconda3/envs/py374/lib/python3.7/site-packages/pysam/__init__.py", line 4, in <module>
    from pysam.libchtslib import *
ImportError: /home/skgtrk2/miniconda3/envs/py374/lib/python3.7/site-packages/pysam/libchtslib.cpython-37m-x86_64-linux-gnu.so: undefined symbol: __intel_sse2_strcpy

Have you seen this before?
Thank you

**Comment by drmjc** [comment]
Hi,
I haven't seen this one. It looks related to this issue when using the
Intel compiler:

https://stackoverflow.com/questions/42611515/undefined-symbol-intel-sse2-strcpy

Cheers
