### ISSUE TITLE
raise ValueError("Missing these files: " + ",".join(missing_files)) ValueError: Missing these files: files

### ISSUE THREAD

**Issue by Jyoti-Mridha** [KCCG/mity#56]
Hi, i am using the following command for mity INDELS finding using ONT generated data, which has been aligned by minimap2 aligner. Here i am using a single BAM file as a input. i am a bit confuse to troubleshoot the error. Any help will be really appreciable. Thank you guys in advance.

The command i am using is :

mity call --reference hg38 --prefix barcode17 --output-dir /pfs/home/jyotimridha/Mito_ONT/Structural_variants/mity/ --normalise files /pfs/home/jyotimridha/Mito_ONT/Batch1_Barcode_Aug_reanalysed/2_minimap_to_freebayes/barcode17_sorted.bam

The error i am facing:

raise ValueError("Missing these files: " + ",".join(missing_files))
ValueError: Missing these files: files

Overall message i am getting on terminal is here:

mity call --reference hg38 --prefix barcode17 --output-dir /pfs/home/jyotimridha/Mito_ONT/Structural_variants/mity/ --normalise files /pfs/home/jyotimridha/Mito_ONT/Batch1_Barcode_Aug_reanalysed/2_minimap_to_freebayes/barcode17_sorted.bam
mity version 1.1.0
Calling mitochondrial variants
Traceback (most recent call last):
  File "/pfs/home/jyotimridha/.conda/envs/fastp/bin/mity", line 33, in <module>
    main()
  File "/pfs/home/jyotimridha/.conda/envs/fastp/bin/mity", line 29, in main
    args.func(args)
  File "/pfs/home/jyotimridha/.conda/envs/fastp/lib/python3.12/site-packages/mitylib/commands.py", line 42, in _cmd_call
    call.Call(
  File "/pfs/home/jyotimridha/.conda/envs/fastp/lib/python3.12/site-packages/mitylib/call.py", line 69, in __init__
    self.run()
  File "/pfs/home/jyotimridha/.conda/envs/fastp/lib/python3.12/site-packages/mitylib/call.py", line 84, in run
    self.run_checks()
  File "/pfs/home/jyotimridha/.conda/envs/fastp/lib/python3.12/site-packages/mitylib/call.py", line 219, in run_checks
    self.check_missing_file(self.files, die=True)
  File "/pfs/home/jyotimridha/.conda/envs/fastp/lib/python3.12/site-packages/mitylib/call.py", line 323, in check_missing_file
    raise ValueError("Missing these files: " + ",".join(missing_files))
ValueError: Missing these files: files

**Comment by trentzz** [comment]
Hi @Jyoti-Mridha,

Mity first tries to look for the files you've specified in the file list. In the command you've specified:

mity call --reference hg38 --prefix barcode17 --output-dir /pfs/home/jyotimridha/Mito_ONT/Structural_variants/mity/ --normalise **files** /pfs/home/jyotimridha/Mito_ONT/Batch1_Barcode_Aug_reanalysed/2_minimap_to_freebayes/barcode17_sorted.bam

"**files**" here is part of the list of files that mity is looking for, and the error is saying that the file called "files" can't be found. I'm assuming that you're not actually trying to use mity on a file named "files", so you can just get rid of it and run this:

```
mity call --reference hg38 --prefix barcode17 --output-dir /pfs/home/jyotimridha/Mito_ONT/Structural_variants/mity/ --normalise /pfs/home/jyotimridha/Mito_ONT/Batch1_Barcode_Aug_reanalysed/2_minimap_to_freebayes/barcode17_sorted.bam
```

Or formatted a bit differently: 
```
mity call \
--reference hg38 \
--prefix barcode17 \
--output-dir /pfs/home/jyotimridha/Mito_ONT/Structural_variants/mity/ \
--normalise \
/pfs/home/jyotimridha/Mito_ONT/Batch1_Barcode_Aug_reanalysed/2_minimap_to_freebayes/barcode17_sorted.bam
```

You don't need to put anything in front of your list of files, and feel free to look at the main readme in the github repo for more examples of how to run the commands.

Thanks! Let me know if you're still encountering issues!
Trent Zeng

**Comment by trentzz** [comment]
Hi @Jyoti-Mridha,

Just wondering if you were able to resolve this problem? I'm going to close this issue as we have new releases out, but feel free to reopen this issue or create a new one if you are still having this issue.

Thanks!
Trent Zeng
