### ISSUE TITLE
application to non-model organisms

### ISSUE THREAD

**Issue by dgs108** [KCCG/mity#57]
I'm interested in using `mity` to assess within-individual variation in mitochondrial DNA. I have assembled mitochondrial genomes for ~300 individuals of a non-model fish species using `MitoZ` and found that 10% of full-sibling pairs have distinct haplotypes (1-8 SNPs). As these individuals share a mother, I believe this variation is due to sequencing artifacts or heteroplasmy. 

Can `mity` be used to examine these issues in non-human samples?

If so, can you please advise on how to prep input files?

I receive the following error after running this code:

```
fastp -i 360387_R1_001.fastq.gz -I 360387_R2_001.fastq.gz -o 360387_R1_001_trim.fastq.gz -O 360387_R2_001_trim.fastq.gz -q 20 --detect_adapter_for_pe
bwa mem mt_reference.fasta 360387_R1_001_trim.fastq.gz 360387_R2_001_trim.fastq.gz > 360387_align.sam
samtools view -@ 40 -S -b 360387_align.sam > 360387_align.bam
samtools sort -@ 40 360387_align.bam -o 360387_align_sort.bam
samtools index -@ 40 360387_align_sort.bam
mity runall 360387_align_sort.bam --prefix test
```

Error: 
```
mity 1.1.0
mity runall
Traceback (most recent call last):
  File "/home/dswift/miniconda3/bin/mity", line 33, in <module>
    main()
  File "/home/dswift/miniconda3/bin/mity", line 29, in main
    args.func(args)
  File "/home/dswift/miniconda3/lib/python3.12/site-packages/mitylib/commands.py", line 388, in _cmd_runall
    call.Call(
  File "/home/dswift/miniconda3/lib/python3.12/site-packages/mitylib/call.py", line 69, in __init__
    self.run()
  File "/home/dswift/miniconda3/lib/python3.12/site-packages/mitylib/call.py", line 84, in run
    self.run_checks()
  File "/home/dswift/miniconda3/lib/python3.12/site-packages/mitylib/call.py", line 222, in run_checks
    if not all(map(self.bam_has_rg, self.files)):
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/dswift/miniconda3/lib/python3.12/site-packages/mitylib/call.py", line 242, in bam_has_rg
    return len(r.header["RG"]) > 0
               ~~~~~~~~^^^^^^
  File "pysam/libcalignmentfile.pyx", line 557, in pysam.libcalignmentfile.AlignmentHeader.__getitem__
KeyError: 'RG'
```

Thanks!

**Comment by trentzz** [comment]
Hi @dgs108,

I'm not too familiar with your use case and I'll have to get back to you on that. Just to explain the error a bit, `mity` requires `RG` headers in the bam file for variant calling purposes, so that's part of the pre-checks are done. This is just saying it couldn't find any `RG` headers present.

Would you know if your bam files have `RG` headers? 

Thanks!

**Comment by dgs108** [comment]
Thanks for the quick response!

I can add RG headers to the bam file. Can I use a reference for my study species, or should I use one of the references provided? It would be great if you could share some code to produce bam files comparable to the test files.

**Comment by trentzz** [comment]
Hi @dgs108,

Unfortunately `mity` does not currently support adding custom references, but it's something we're planning on adding in future releases! We only have references for human and mice at the moment, and it probably won't work that well for your use case.

Thanks!
Trent

**Comment by trentzz** [comment]
Hi @dgs108,

Just letting you know that we have added functionality for custom reference files now in the latest release of mity.

You can see this in the [changelog](https://github.com/KCCG/mity/blob/master/docs/change_log.md) for 2.0.0.

> Added `--custom-reference-fasta` and `--custom-reference-genome` options for `mity call`, `mity normalise` and `mity runall`

Feel free to reopen this issue or create a new one if you have any follow up questions or concerns with this.

Thanks!
Trent Zeng
