### ISSUE TITLE
Ad not in list

### ISSUE THREAD

**Issue by DiyaVaka** [KCCG/mity#7]
After running mity call i tried running mity normalise and it says AD not in list. I checked the vcf file produced by freebayes and it does not have AD. How to resolve this?

Thanks

DIya

**Comment by drmjc** [comment]
Hi, I have not experienced this. Can you provide a reproducible example and the command line that you used? thanks.

**Comment by master-noddy** [comment]
I also got this error, not able to resolve it.
Please see the command and the output

time mity call --reference hg38 --prefix DEMO --normalise 21A0003630-21IN000470_60307-CREV3_recal.cram.bam 21A0001020-21IN000165_59412-CREV3_recal.cram.bam --out-folder-path output/ --debug                                                                     mity version 0.3.0
Calling mitochondrial variants
Running FreeBayes in sensitive mode
Traceback (most recent call last):
  File "/root/anaconda3/envs/mity/bin/mity", line 29, in <module>
    args.func(args)
  File "/root/anaconda3/envs/mity/lib/python3.7/site-packages/mitylib/commands.py", line 54, in _cmd_call
    args.out_folder_path, args.region)
  File "/root/anaconda3/envs/mity/lib/python3.7/site-packages/mitylib/call.py", line 108, in do_call
    vcfnorm(vcf=unnormalised_vcf_path, out_file=output_file_name, p=p, genome=genome)
  File "/root/anaconda3/envs/mity/lib/python3.7/site-packages/mitylib/normalise.py", line 1313, in do_normalise
    single_allele = split_multi_allelic(variants)
  File "/root/anaconda3/envs/mity/lib/python3.7/site-packages/mitylib/normalise.py", line 233, in split_multi_allelic
    AD_idx = FORMAT_name.index("AD")
ValueError: 'AD' is not in list

**Comment by drmjc** [comment]
Hi, can you share your bam files, preferably just those ones with reads in chrM, so I can reproduce this error? Thanks

**Comment by DiyaVaka** [comment]
Hi,

My error was resolved after I had a supported version of freebayes installed.

Dedeepya Vaka
Bioinformatics Programmer IV
Institute of Human Genetics
513 Parnassus Ave., HSE S965E
San Franscisco, CA 94143
W 415-502-3570
***@***.***


________________________________

**Comment by drmjc** [comment]
Great, thanks for letting me know. I'm curious what version threw the error?

Thanks

**Comment by Pharmacogenetecist** [comment]
I am getting a similar issue trying to run one of the test files:
(MITY)  mity call --prefix ashkenazim --out-folder-path "/Mity/testOUT/" --region MT:1-500 --normalise "/Mity/test_in/HG002.hs37d5.2x250.small.MT.RG.bam"
Found dependency: /anaconda3/envs/MITY/bin/freebayes
Found dependency: /anaconda3/envs/MITY/bin/gsort
Found dependency: /anaconda3/envs/MITY/bin/tabix
Found dependency: /anaconda3/envs/MITY/bin/bgzip
Found dependency: /anaconda3/envs/MITY/bin/python
Found dependency: /anaconda3/envs/MITY/bin/mity
mity version 0.4.0
Calling mitochondrial variants
Running FreeBayes in sensitive mode
Traceback (most recent call last):
  File "/anaconda3/envs/MITY/bin/mity", line 29, in <module>
    args.func(args)
  File "/anaconda3/envs/MITY/lib/python3.7/site-packages/mitylib/commands.py", line 53, in _cmd_call
    args.out_folder_path, args.region)
  File "/anaconda3/envs/MITY/lib/python3.7/site-packages/mitylib/call.py", line 108, in do_call
    vcfnorm(vcf=unnormalised_vcf_path, out_file=output_file_name, p=p, genome=genome)
  File "/anaconda3/envs/MITY/lib/python3.7/site-packages/mitylib/normalise.py", line 1313, in do_normalise
    single_allele = split_multi_allelic(variants)
  File "/anaconda3/envs/MITY/lib/python3.7/site-packages/mitylib/normalise.py", line 233, in split_multi_allelic
    AD_idx = FORMAT_name.index("AD")
ValueError: 'AD' is not in list

**Comment by trentzz** [comment]
Hi, the issues you've mentioned should be resolved in the new release of Mity 1.1.0. If you encounter any further problems, please feel free to open a new issue. Thanks!
